version: "3.7"
services:
  characters_api:
    restart: always
    build: https://github.com/Borken/characters_microservice.git
    expose:
      - "8082"
    command: flask run --host=0.0.0.0 --port 8082
    depends_on:
      - postgres_characters
  places_api:
    restart: always
    build: https://github.com/Borken/places_microservice.git
    expose:
      - "8081"
    command: flask run --host=0.0.0.0 --port 8081
    depends_on:
      - postgres_places
  juego_de_tornos_api:
    restart: always
    build: https://github.com/Borken/juego_de_tornos_microservice.git
    ports:
      - "8083:8083"
    command: flask run --host=0.0.0.0 --port 8083
    depends_on:
      - places_api
      - characters_api
  postgres_characters:
    restart: always
    build: ./characters_microservice/postgresql
    volumes:
      - /var/lib/postgresql
    expose:
      - "5432"
  postgres_places:
    restart: always
    build: ./places_microservice/postgresql
    volumes:
      - /var/lib/postgresql
    expose:
      - "5431"